# Generated by Django 4.2 on 2025-03-10 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorias', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/')),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.produccion')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidades', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('categoriaColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categoriacolor')),
                ('categoriaGenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categoriagenero')),
                ('categoriaPrenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categoriaprenda')),
                ('categoriaTalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categoriatalla')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
    ]
