# Generated by Django 5.1.7 on 2025-03-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock_maximo',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
