# Generated by Django 4.2 on 2024-12-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=set(),
        ),
    ]
