# Generated by Django 5.1.7 on 2025-03-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_productos_precio_compra_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='precio_compra_unitario',
            new_name='precio_compra_unitario_de_fabrica',
        ),
    ]
