# Generated by Django 4.2 on 2025-03-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_precio_compra_unitario_productos_precio_compra_unitario_de_fabrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_agregada', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
            ],
        ),
    ]
