# Generated by Django 4.2 on 2025-03-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_precio_compra_unitario_productos_precio_compra_unitario_de_fabrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='stock_maximo',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(default=20),
        ),
    ]
