# Generated by Django 4.2 on 2025-03-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_stock_maximo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(default=8),
        ),
    ]
