# Generated by Django 4.2 on 2025-03-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_historialentradainventario'),
        ('inventario', '0006_alter_inventario_stock_minimo'),
    ]

    operations = [
    ]
