# Generated by Django 4.2 on 2025-03-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_merge_20250328_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSalidaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida', models.PositiveIntegerField()),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='inventario.inventario')),
            ],
        ),
    ]
