# Generated by Django 4.2 on 2025-03-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaitem',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
