# Generated by Django 4.2 on 2025-03-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='nombreCliente',
            new_name='nombre_cliente',
        ),
    ]
