# Generated by Django 4.2 on 2025-03-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaColor',
            fields=[
                ('idCategoriaC', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaGenero',
            fields=[
                ('idCategoriaG', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPrenda',
            fields=[
                ('idCategoriaP', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaTalla',
            fields=[
                ('idCategoriaT', models.AutoField(primary_key=True, serialize=False)),
                ('tipoTalla', models.CharField(max_length=40)),
                ('talla', models.CharField(max_length=12)),
            ],
        ),
    ]
