# Generated by Django 4.2 on 2024-12-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaColor',
            fields=[
                ('idCategoriaC', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('ROJO', 'ROJO'), ('AZUL', 'AZUL'), ('AMARILLO', 'AMARILLO'), ('VINOTINTO', 'VINOTINTO'), ('BEIGE', 'BEIGE'), ('MORADO', 'MORADO'), ('VERDE', 'VERDE'), ('LIMA', 'LIMA'), ('CAFE', 'CAFE'), ('AZULREY', 'AZULREY'), ('GRIS', 'GRIS'), ('NEGRO', 'NEGRO')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaGenero',
            fields=[
                ('idCategoriaG', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER'), ('NIÑO', 'NIÑO'), ('NIÑA', 'NIÑA')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPrenda',
            fields=[
                ('idCategoriaP', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(choices=[('CAMISETAS', 'CAMISETAS'), ('CAMISAS', 'CAMISAS'), ('CHAQUETAS', 'CHAQUETAS'), ('PANTALONES', 'PANTALONES'), ('MEDIAS', 'MEDIAS'), ('SACOS', 'SACOS'), ('GUANTES', 'GUANTES')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaTalla',
            fields=[
                ('idCategoriaT', models.AutoField(primary_key=True, serialize=False)),
                ('tipoTalla', models.CharField(choices=[('CALZADO', 'CALZADO'), ('PRENDA', 'PRENDA')], max_length=40)),
                ('talla', models.CharField(max_length=12)),
            ],
        ),
    ]
