# Generated by Django 4.2 on 2025-02-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacolor',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='categoriagenero',
            name='genero',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='categoriaprenda',
            name='nombreCategoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='categoriatalla',
            name='tipoTalla',
            field=models.CharField(max_length=40),
        ),
    ]
