# Generated by Django 4.2 on 2024-12-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('idProduccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=250)),
                ('nombreProveedor', models.CharField(max_length=70)),
                ('cantidad', models.IntegerField()),
                ('materiales', models.CharField(max_length=70)),
                ('costoProduccion', models.DecimalField(decimal_places=2, max_digits=23)),
                ('fecha_finalizacion', models.DateField()),
            ],
        ),
    ]
