# Generated by Django 4.2 on 2024-12-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_alter_inventario_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='transportistas',
            fields=[
                ('idTransportista', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('EN ENTREGA', 'EN ENTREGA')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='VentaPedido',
            fields=[
                ('idVentaPedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombresCliente', models.CharField(max_length=25)),
                ('apellidosCliente', models.CharField(max_length=25)),
                ('cantidad', models.PositiveIntegerField()),
                ('fechaPedido', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccion', models.CharField(max_length=50)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='logistica',
            fields=[
                ('idLogistica', models.AutoField(primary_key=True, serialize=False)),
                ('costoEnvio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccion', models.CharField(max_length=50)),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.transportistas')),
                ('ventapedidoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.ventapedido')),
            ],
        ),
    ]
