# Generated by Django 4.2 on 2025-03-10 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('idTransportista', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('EN ENTREGA', 'EN ENTREGA')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('idLogistica', models.AutoField(primary_key=True, serialize=False)),
                ('costoEnvio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccion', models.CharField(max_length=50)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.orden')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.transportista')),
            ],
        ),
    ]
